#### EX1

In [2]:
import pandas as pd

df = pd.read_csv ( 'DelayedFlights.csv',index_col=0)   #  index_col=0  trec la columna nonamed 
                                      #df.shape #shape es un atribut i ens diu el numero de files X columnes  que té
df = df.sample(n = 200000)            # agafo del dataframe 200.000 files aleatòries

                                 # Dimensions del dataset
print(df.shape)                  # El dataset te 200.000 instacies y 30 atributs(columnes)

                                 
print(df.head(20))               # Mostra els 20 primers
print ("                                                                 ")
print (df.columns)               # Mostra les columnes del dataset
print ("                                                                 ")

print ("                                                                 ")

print ("                                                                 ")
df.info()                        # Ens diu les dades que té i ens diu si hi ha alguna columna que n'hi falten
                                 #les columnes que li falten valors son:
                                 # ArrTime, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay,
                                 #TaxiIn,  CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay
            
            # dtype ens diu el tipus de dades que té: # int64   enter de 64bits
                                                      # float64  números flotants o numeros amb decimals
                                                      # object   tipus de dades de text
            # NaN not a number (no és un número)

(200000, 29)
         Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
5952800  2008     11           6          4    644.0         620    655.0
3224893  2008      6          14          6   1227.0        1131   1423.0
3721618  2008      7          20          7   2127.0        2110   2234.0
4729036  2008      8          30          6   1340.0        1330   1628.0
2816033  2008      5           2          5   1717.0        1704   2015.0
1064848  2008      2          21          4   1618.0        1425   2003.0
5247788  2008      9          22          1   1424.0        1334   1627.0
936825   2008      2          22          5    834.0         825   1035.0
3251380  2008      6          24          2   1833.0        1603   2008.0
1100105  2008      2           5          2   1832.0        1615   2046.0
4828021  2008      8           4          1   1919.0        1910   2147.0
2206988  2008      4          11          5   2354.0        2229     56.0
5824936  2008     10          26          7   1536.0        1520   2354.0
1826909  2008      4          14          1   1052.0        1025   1136.0
3701574  2008      7           9          3   2118.0        1814   2336.0
1215360  2008      3          15          6   1644.0        1625   1647.0
419499   2008      1          11          5   1701.0        1645   1817.0
3300973  2008      6          20          5   1934.0        1859   2305.0
560037   2008      1          26          6      5.0        2345    328.0
1632984  2008      3           8          6   1023.0        1010   1257.0

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
5952800         645            WN       3190  ...    8.0      6.0          0
3224893        1316            UA        339  ...    8.0     12.0          0
3721618        2227            XE       2165  ...    5.0     12.0          0
4729036        1630            AA        809  ...    5.0     14.0          0
2816033        2006            NW        294  ...    9.0     18.0          0
1064848        1745            AA        644  ...   11.0     28.0          0
5247788        1552            NW       1724  ...    9.0     11.0          0
936825          949            F9        557  ...   22.0     22.0          0
3251380        1737            UA       1524  ...    8.0     17.0          0
1100105        1840            AA       2360  ...    7.0     22.0          0
4828021        2150            DL        167  ...    8.0     44.0          0
2206988        2323            NW        120  ...    6.0     15.0          0
5824936        2345            AA         20  ...   12.0     18.0          0
1826909        1115            WN          9  ...    3.0      8.0          0
3701574        2038            XE       3068  ...    8.0     32.0          0
1215360        1630            WN       2339  ...    2.0      6.0          0
419499         1805            MQ       4754  ...   22.0     21.0          0
3300973        2206            DL       1463  ...    4.0     58.0          0
560037          340            B6        767  ...    4.0      8.0          0
1632984        1147            NW       1692  ...    9.0     51.0          0

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
5952800                 N         0           NaN          NaN      NaN
3224893                 N         0           0.0          0.0     11.0
3721618                 N         0           NaN          NaN      NaN
4729036                 N         0           NaN          NaN      NaN
2816033                 N         0           NaN          NaN      NaN
1064848                 N         0           6.0          0.0     25.0
5247788                 N         0           3.0          0.0      0.0
936825                  N         0           0.0          0.0     37.0
3251380                 N         0          47.0          0.0      1.0
1100105                 N         0           0.0          0.0     71.0
4828021                 N         0           NaN          NaN      NaN
2206988                 N         0           7.0          0.0      8.0
5824936                 N         0           NaN          NaN      NaN
1826909                 N         0           0.0          0.0      0.0
3701574                 N         0           6.0          0.0      0.0
1215360                 N         0           0.0          0.0      0.0
419499                  N         0           NaN          NaN      NaN
3300973                 N         0           0.0          0.0     24.0
560037                  N         0           NaN          NaN      NaN
1632984                 N         0          13.0          0.0     57.0

         SecurityDelay  LateAircraftDelay
5952800            NaN                NaN
3224893            0.0               56.0
3721618            NaN                NaN
4729036            NaN                NaN
2816033            NaN                NaN
1064848            0.0              107.0
5247788            0.0               32.0
936825             0.0                9.0
3251380            0.0              103.0
1100105            0.0               55.0
4828021            NaN                NaN
2206988            0.0               78.0
5824936            NaN                NaN
1826909            0.0               21.0
3701574            0.0              172.0
1215360            0.0               17.0
419499             NaN                NaN
3300973            0.0               35.0
560037             NaN                NaN
1632984            0.0                0.0

[20 rows x 29 columns]

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')



<class 'pandas.core.frame.DataFrame'>
Int64Index: 200000 entries, 5952800 to 1571341
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Year               200000 non-null  int64
 1   Month              200000 non-null  int64
 2   DayofMonth         200000 non-null  int64
 3   DayOfWeek          200000 non-null  int64
 4   DepTime            200000 non-null  float64
 5   CRSDepTime         200000 non-null  int64
 6   ArrTime            199318 non-null  float64
 7   CRSArrTime         200000 non-null  int64
 8   UniqueCarrier      200000 non-null  object
 9   FlightNum          200000 non-null  int64
 10  TailNum            200000 non-null  object
 11  ActualElapsedTime  199185 non-null  float64
 12  CRSElapsedTime     199986 non-null  float64
 13  AirTime            199185 non-null  float64
 14  ArrDelay           199185 non-null  float64
 15  DepDelay           200000 non-null  float64
 16  Origin             200000 non-null  object
 17  Dest               200000 non-null  object
 18  Distance           200000 non-null  int64
 19  TaxiIn             199318 non-null  float64
 20  TaxiOut            199961 non-null  float64
 21  Cancelled          200000 non-null  int64
 22  CancellationCode   200000 non-null  object
 23  Diverted           200000 non-null  int64
 24  CarrierDelay       129176 non-null  float64
 25  WeatherDelay       129176 non-null  float64
 26  NASDelay           129176 non-null  float64
 27  SecurityDelay      129176 non-null  float64
 28  LateAircraftDelay  129176 non-null  float64
dtypes: float64(14), int64(10), object(5)
memory usage: 45.8+ MB

### Ex2

In [6]:
import pandas as pd

df = pd.read_csv ( 'DelayedFlights.csv', index_col=0) 
                                       #df.shape #shape es un atribut i ens diu el numero de files X columnes 30 que te
df = df.sample(n = 200000)             # agafo del dataframe 20 files aleatòries

len(df.columns)                  
pd.options.display.max_columns = 50    # li demano que mostri totes les columnes  i no posi ...

                                 # Descripció del dataset
print(df.describe())             # Com es distribueixen les variables númeriques
                                 # count número de registres de cada columna
                                 # mean mitjana dels valors de cada columna
                                 # std desviació standard
                                 # min  valor de la columna
                                 # 25% 75% els quantils
                                 # 50% la mediana
                                 # max màxim valor de la columna
df.shape
                                 # #shape es un atribut i ens diu el numero de files X columnes 30 que té

           Year         Month     DayofMonth      DayOfWeek        DepTime  \
count  200000.0  200000.00000  200000.000000  200000.000000  200000.000000
mean     2008.0       6.11746      15.748065       3.981645    1517.653080
std         0.0       3.48584       8.767346       1.995665     451.161054
min      2008.0       1.00000       1.000000       1.000000       1.000000
25%      2008.0       3.00000       8.000000       2.000000    1202.000000
50%      2008.0       6.00000      16.000000       4.000000    1545.000000
75%      2008.0       9.00000      23.000000       6.000000    1900.000000
max      2008.0      12.00000      31.000000       7.000000    2400.000000

          CRSDepTime        ArrTime     CRSArrTime      FlightNum  \
count  200000.000000  199264.000000  200000.000000  200000.000000
mean     1466.416780    1607.433154    1632.245875    2186.535705
std       425.229233     549.755257     465.935322    1946.463756
min         1.000000       1.000000       0.000000       1.000000
25%      1132.000000    1314.000000    1323.000000     609.000000
50%      1510.000000    1714.000000    1705.000000    1544.000000
75%      1815.000000    2030.000000    2013.000000    3422.000000
max      2359.000000    2400.000000    2400.000000    7829.000000

       ActualElapsedTime  CRSElapsedTime        AirTime       ArrDelay  \
count      199148.000000   199976.000000  199148.000000  199148.000000
mean          133.028321      134.027748     107.995169      42.400782
std            71.998526       71.264622      68.543951      56.790854
min            14.000000      -21.000000       6.000000     -69.000000
25%            80.000000       82.000000      58.000000       9.000000
50%           116.000000      116.000000      90.000000      25.000000
75%           165.000000      165.000000     137.000000      56.000000
max           702.000000      660.000000     641.000000    1392.000000

            DepDelay       Distance         TaxiIn        TaxiOut  \
count  200000.000000  200000.000000  199264.000000  199963.000000
mean       43.374500     763.743825       6.805590      18.248871
std        53.415648     574.157651       5.213479      14.540098
min         6.000000      30.000000       0.000000       0.000000
25%        12.000000     337.000000       4.000000      10.000000
50%        24.000000     606.000000       6.000000      14.000000
75%        54.000000     997.000000       8.000000      21.000000
max      1369.000000    4962.000000     175.000000     393.000000

           Cancelled       Diverted   CarrierDelay   WeatherDelay  \
count  200000.000000  200000.000000  129242.000000  129242.000000
mean        0.000290       0.003970      19.371636       3.658385
std         0.017027       0.062883      43.489364      21.039489
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       2.000000       0.000000
75%         0.000000       0.000000      21.000000       0.000000
max         1.000000       1.000000    1369.000000    1027.000000

            NASDelay  SecurityDelay  LateAircraftDelay
count  129242.000000  129242.000000      129242.000000
mean       14.996247       0.087727          25.287058
std        33.671594       2.046631          42.254241
min         0.000000       0.000000           0.000000
25%         0.000000       0.000000           0.000000
50%         2.000000       0.000000           8.000000
75%        14.000000       0.000000          34.000000
max       865.000000     280.000000        1002.000000

(200000, 29)

In [8]:
import pandas as pd     #ok borrar columnes, mostrar quants valors falten per columna 

df = pd.read_csv ( 'DelayedFlights.csv',index_col=0) 
df.shape                             # shape es un atribut i ens diu el numero de files X columnes que té
df = df.sample(n= 200000)            # agafo del dataframe 200000 files aleatòries
                                     # redueixo  les columnes  del dataframe usant drop


reduit = df.drop(["Month","DayofMonth","CRSDepTime","CRSArrTime","DayOfWeek","TaxiOut","TaxiIn","Cancelled","CancellationCode","Diverted","TailNum","ActualElapsedTime","CRSElapsedTime"] , axis=1)
reduit.isna().sum()                         # dades faltants al dataframe  suma les que falten en cada columna
    

# per contestar al que es demana agafare les columnes que tenen a veure amb les causes dels retards
# la columna year, és informativa per situar-nos al context de l analisi i les columnes origin dest distance airTime ArrDelay FlightNum
# son columnes que utilitzo per respondre les preguntes de ex 2 .  la columna uniquecarrier es el nom de
# les companyies aerees que son analitzades

Year                     0
DepTime                  0
ArrTime                741
UniqueCarrier            0
FlightNum                0
AirTime                878
ArrDelay               878
DepDelay                 0
Origin                   0
Dest                     0
Distance                 0
CarrierDelay         71209
WeatherDelay         71209
NASDelay             71209
SecurityDelay        71209
LateAircraftDelay    71209
dtype: int64

In [1]:
import numpy as np
import pandas as pd     #0k vols enderrerits

df = pd.read_csv ( 'DelayedFlights.csv',index_col=0)      #creo una columna nova totalDelay amb la suma  
df = df.sample(n = 200000)                                #de tots els edarreriments( vull dir. sumo  tots els valors 
                                                          # de les columnes que contenen retards) amb np.nan_to_num, 
                                                          #puc convertir en 0 el valor NaN

df["totalDelay"] = np.nan_to_num(df['ArrDelay']) + np.nan_to_num(df['DepDelay']) + np.nan_to_num(df['CarrierDelay']) + np.nan_to_num(df['WeatherDelay']) + np.nan_to_num(df['NASDelay']) + np.nan_to_num(df['SecurityDelay']) + np.nan_to_num(df['LateAircraftDelay'])

print(df[["UniqueCarrier","ArrDelay","totalDelay"]])

agrupado = df.groupby(['UniqueCarrier']).agg({'totalDelay': 'sum'}).sort_values(by='totalDelay', ascending=False);

print(agrupado)    # agrupo les companyies 'UniqueCarrier'amb groupby   i, amb    totalDelay obtinc el total de les sumes
                   # dels endarreriments 
                   # sort_values els ordena de més gran a mes petit

        UniqueCarrier  ArrDelay  totalDelay
5916900            CO     -11.0        -5.0
2916187            AA      -1.0        10.0
5290649            AA      35.0        90.0
1763983            CO      84.0       263.0
3242773            UA      12.0        37.0
...               ...       ...         ...
5949343            WN      10.0        27.0
192096             OO      86.0       249.0
6416918            B6       7.0        20.0
834277             UA       3.0        25.0
1079889            AA      11.0        41.0

[200000 rows x 3 columns]
               totalDelay
UniqueCarrier
WN              3607556.0
AA              2737728.0
UA              2175028.0
MQ              1931402.0
OO              1816780.0
XE              1579517.0
DL              1401670.0
CO              1269257.0
EV              1224276.0
YV              1156657.0
US              1105290.0
NW              1032601.0
FL               930417.0
B6               921843.0
OH               796160.0
9E               742201.0
AS               439286.0
F9               232275.0
HA                74586.0
AQ                 5176.0

In [2]:
import numpy as np
import pandas as pd     #0k quin son els mes llargs i més retards

df = pd.read_csv ('DelayedFlights.csv',index_col=0)
df = df.sample(n = 200000)


df.sort_values(by='Distance', ascending=False).head(10)   # ordena els valors de la columna distance de + gran a més petit
print(df[['UniqueCarrier','FlightNum','Origin','Dest','Distance']])


dfdel = df.sort_values(by='ArrDelay', ascending=False).head(10)        # ordena els valors de ArrDelay ascendent  retards
print(dfdel[['UniqueCarrier','FlightNum','ArrDelay']])

        UniqueCarrier  FlightNum Origin Dest  Distance
2643516            UA       1582    SFO  LAS       414
4032403            MQ       4335    PNS  ORD       794
4027231            MQ       4156    SYR  ORD       607
6513588            WN       1485    DAL  MCI       461
1666549            AA        424    DFW  BOS      1562
...               ...        ...    ...  ...       ...
3590587            DL        177    ATL  MCO       403
3574249            CO        769    LAS  EWR      2227
4118199            AA       1090    LAS  MIA      2175
3227653            UA        408    DEN  LGA      1619
1844773            WN       1199    MCO  PHX      1848

[200000 rows x 5 columns]
        UniqueCarrier  FlightNum  ArrDelay
2832617            NW       1107    1951.0
1634129            NW       1743    1490.0
6868167            NW       1196    1395.0
5524147            NW       1765    1392.0
4117650            AA       1073    1337.0
1097934            AA       2233    1312.0
6916589            AA       1138    1312.0
1022917            NW       1117    1253.0
2837951            NW       1509    1177.0
5784341            NW        398    1148.0

### EX3

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
2643516,2008,5,9,5,2010.0,1930,2145.0,2101,UA,1582,...,8.0,19.0,0,N,0,0.0,0.0,8.0,0.0,36.0
4032403,2008,7,23,3,1307.0,1145,1534.0,1410,MQ,4335,...,6.0,10.0,0,N,0,0.0,0.0,2.0,0.0,82.0
4027231,2008,7,10,4,2233.0,1805,2329.0,1905,MQ,4156,...,10.0,11.0,0,N,0,0.0,0.0,264.0,0.0,0.0
6513588,2008,12,18,4,1339.0,1310,1459.0,1435,WN,1485,...,4.0,10.0,0,N,0,8.0,0.0,0.0,0.0,16.0
1666549,2008,3,21,5,1158.0,1150,1622.0,1620,AA,424,...,7.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3590587,2008,6,9,1,1712.0,1650,1857.0,1828,DL,177,...,6.0,37.0,0,N,0,22.0,0.0,7.0,0.0,0.0
3574249,2008,6,16,1,955.0,838,1738.0,1645,CO,769,...,16.0,21.0,0,N,0,0.0,0.0,53.0,0.0,0.0
4118199,2008,7,30,3,613.0,600,1351.0,1340,AA,1090,...,7.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3227653,2008,6,3,2,1802.0,1756,2326.0,2336,UA,408,...,4.0,20.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1844773,2008,4,19,6,1757.0,1735,1944.0,1925,WN,1199,...,4.0,7.0,0,N,0,5.0,0.0,0.0,0.0,14.0

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv ( 'DelayedFlights.csv',index_col=0) 
df.shape                             # shape es un atribut i ens diu el numero de files X columnes que té
df = df.sample(n= 200000)            # agafo del dataframe 200000 files aleatòries
                                     # redueixo  les columnes  del dataframe usant drop
    
    
df["totalDelay"] = np.nan_to_num(df['ArrDelay']) + np.nan_to_num(df['DepDelay']) + np.nan_to_num(df['CarrierDelay']) + np.nan_to_num(df['WeatherDelay']) + np.nan_to_num(df['NASDelay']) + np.nan_to_num(df['SecurityDelay']) + np.nan_to_num(df['LateAircraftDelay'])


df["velocitat_mitjana"] = df["Distance"] / (df["AirTime"] / 60) 
  
df["retard"] = df["ArrDelay"] > 0 

len(df.columns)
pd.options.display.max_columns = 40
kk=df.drop(["Month","DayofMonth","CRSDepTime","CRSArrTime","DayOfWeek","TaxiOut","TaxiIn","Cancelled","CancellationCode","Diverted","TailNum","ActualElapsedTime","CRSElapsedTime"] , axis=1)
kk

,Year,DepTime,ArrTime,UniqueCarrier,FlightNum,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,totalDelay,velocitat_mitjana,retard
1121624,2008,1730.0,1902.0,B6,6,63.0,1.0,10.0,JFK,BUF,301,NaN,NaN,NaN,NaN,NaN,11.0,286.666667,True
3030159,2008,1448.0,1523.0,WN,3657,84.0,28.0,28.0,CLE,STL,487,1.0,0.0,0.0,0.0,27.0,84.0,347.857143,True
4399221,2008,1004.0,1117.0,OH,5508,39.0,-5.0,14.0,JFK,BOS,187,NaN,NaN,NaN,NaN,NaN,9.0,287.692308,False
4104891,2008,718.0,1030.0,AA,452,172.0,15.0,13.0,MIA,BOS,1258,13.0,0.0,2.0,0.0,0.0,43.0,438.837209,True
479898,2008,2204.0,602.0,AA,272,281.0,2.0,14.0,SFO,MIA,2585,NaN,NaN,NaN,NaN,NaN,16.0,551.957295,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210381,2008,850.0,1044.0,WN,3570,100.0,4.0,10.0,OAK,SEA,671,NaN,NaN,NaN,NaN,NaN,14.0,402.600000,True
3426755,2008,1735.0,1907.0,NW,352,52.0,104.0,95.0,MSY,MEM,349,0.0,0.0,9.0,0.0,95.0,303.0,402.692308,True
1514219,2008,1620.0,1909.0,EV,4573,90.0,79.0,83.0,MLI,ATL,633,0.0,0.0,79.0,0.0,0.0,241.0,422.000000,True
1686053,2008,1524.0,1835.0,AA,1280,110.0,6.0,24.0,DEN,ORD,888,NaN,NaN,NaN,NaN,NaN,30.0,484.363636,True
132271,2008,1700.0,1803.0,YV,7373,51.0,119.0,58.0,FWA,ORD,157,0.0,0.0,119.0,0.0,0.0,296.0,184.705882,True

In [7]:
pwd

'C:\\Users\\estdo\\itacademy\\ProvesImportarCSV'

In [8]:
kk.to_excel('C:\\Users\\estdo\\itacademy\\ProvesImportarCSV/delay_kk_noind.xlsx', index=False)